export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGN_LOADING = 'SIGN_LOADING';
export const SIGN_ERROR = 'SIGN_ERROR';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_DATA = 'PROFILE_DATA';

export const CHAT_LOADING = 'CHAT_LOADING';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CHAT_DATA = 'CHAT_DATA';
export const CHAT_UNSUBSCRIBE = 'CHAT_UNSUBSCRIBE';
export const FILE_LOADING = 'FILE_LOADING';
export const PROFILE_CHAT_LOADING = 'PROFILE_CHAT_LOADING';
export const PROFILE_CHAT_DATA = 'PROFILE_CHAT_DATA';
export const VIPE_PROFILE = 'VIPE_PROFILE';

export const USERS_DATA = 'USERS_DATA';
export const USERS_LOADING = 'USERS_LOADING';
